apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: default
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.apo-llm-test.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: default
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prometheus.apo-llm-test.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-mcp-tls
  namespace: default
spec:
  secretName: data-mcp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - data-mcp.apo-llm-test.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcp-client-tls
  namespace: default
spec:
  secretName: mcp-client-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - mcp-client.apo-llm-test.com
