apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: croc-shop-monitoring
spec:
  parentRefs:
    - name: cilium-gateway-application-gateway
      namespace: default
      sectionName: https-grafana
  hostnames:
    - "grafana.apo-llm-test.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          namespace: croc-shop-monitoring
          port: 3000
