apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: frontend-to-services
  namespace: crock-shop-product-catalog
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["crock-shop-frontend", "istio-system"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: frontend-to-user
  namespace: crock-shop-user
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["crock-shop-frontend", "istio-system"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: frontend-to-cart
  namespace: crock-shop-cart
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["crock-shop-frontend", "istio-system"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: frontend-to-order
  namespace: crock-shop-order
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["crock-shop-frontend", "istio-system"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-catalog-to-postgres
  namespace: crock-shop-data
spec:
  selector:
    matchLabels:
      app: postgres
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["5432"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: cart-to-redis
  namespace: crock-shop-data
spec:
  selector:
    matchLabels:
      app: redis
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["6379"]
