apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: crock-shop-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: crock-shop-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - crock-shop-gateway
  http:
  - match:
    - uri:
        prefix: /api/products
    route:
    - destination:
        host: product-catalog.crock-shop-product-catalog.svc.cluster.local
        port:
          number: 3001
  - match:
    - uri:
        prefix: /api/auth
    - uri:
        prefix: /api/users
    route:
    - destination:
        host: user.crock-shop-user.svc.cluster.local
        port:
          number: 3002
  - match:
    - uri:
        prefix: /api/cart
    route:
    - destination:
        host: cart.crock-shop-cart.svc.cluster.local
        port:
          number: 3003
  - match:
    - uri:
        prefix: /api/orders
    route:
    - destination:
        host: order.crock-shop-order.svc.cluster.local
        port:
          number: 3004
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.crock-shop-frontend.svc.cluster.local
        port:
          number: 80
