apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop
  labels:
    name: croc-shop
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-frontend
  labels:
    name: croc-shop-frontend
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-product-catalog
  labels:
    name: croc-shop-product-catalog
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-user
  labels:
    name: croc-shop-user
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-cart
  labels:
    name: croc-shop-cart
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-order
  labels:
    name: croc-shop-order
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-data
  labels:
    name: croc-shop-data
    istio-injection: enabled
    app: croc-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: croc-shop-monitoring
  labels:
    name: croc-shop-monitoring
    istio-injection: enabled
    app: croc-shop
